webtalk_init -webtalk_dir /DIST/home/asoehn/Syma_Flight_Final/Syma_Flight_Final.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 23 12:08:06 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2014.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "206284492_177900754_210593007_463" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "6ev2s9vuae2i4vko9tqfb94v53" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2014.4_24" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "24" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 10.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD FX(tm)-6300 Six-Core Processor             " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1448273359000" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key hwid -value "1443617361000" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key bspid -value "1443617383000" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1448273359000"
webtalk_add_data -client sdk -key uid -value "1448275964000" -context "sdk\\\\application/1448275964000"
webtalk_add_data -client sdk -key hwid -value "1443617361000" -context "sdk\\\\application/1448275964000"
webtalk_add_data -client sdk -key bspid -value "1443617383000" -context "sdk\\\\application/1448275964000"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1448275964000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1448275964000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1448275964000"
webtalk_transmit -clientid 1248028691 -regid "206284492_177900754_210593007_463" -xml /DIST/home/asoehn/Syma_Flight_Final/Syma_Flight_Final.sdk/webtalk/usage_statistics_ext_sdk.xml -html /DIST/home/asoehn/Syma_Flight_Final/Syma_Flight_Final.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /DIST/home/asoehn/Syma_Flight_Final/Syma_Flight_Final.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
