# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Test_AXI_Master_simple_v1_0_hw_1_wrapper_2.xdc

# Block Designs: bd/Test_AXI_Master_simple_v1_0_hw_1/Test_AXI_Master_simple_v1_0_hw_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_2/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_Syma_Ctrl_0_2/Test_AXI_Master_simple_v1_0_hw_1_Syma_Ctrl_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_Syma_Ctrl_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_Syma_Ctrl_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_spi_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_spi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_spi_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_spi_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_xbar_0_2/Test_AXI_Master_simple_v1_0_hw_1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_xbar_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_xbar_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_general_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_general_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_general_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_interconnect_general_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_xbar_1_2/Test_AXI_Master_simple_v1_0_hw_1_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_xbar_1 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_xbar_1}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_concat_irq_0_2/Test_AXI_Master_simple_v1_0_hw_1_concat_irq_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_concat_irq_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_concat_irq_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_util_vector_logic_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_util_vector_logic_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_util_vector_logic_0_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0_1/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0}]

# IP: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1_1/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1}]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_2/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_2/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0}] {/inst }]/inst ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_2/Test_AXI_Master_simple_v1_0_hw_1_clk_wiz_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0}]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0}]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_sys_reset_0_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0}]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_axi_timer_0_0_ooc.xdc

# XDC: ipshared/xilinx.com/jtag_axi_v1_0/ede2cda2/constraints/jtag_axi.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0 || ORIG_REF_NAME==Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0}]

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0_2/Test_AXI_Master_simple_v1_0_hw_1_jtag_axi_0_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_xbar_0_2/Test_AXI_Master_simple_v1_0_hw_1_xbar_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_xbar_1_2/Test_AXI_Master_simple_v1_0_hw_1_xbar_1_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0_1/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_0_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/ip/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1_1/Test_AXI_Master_simple_v1_0_hw_1_auto_pc_1_ooc.xdc

# XDC: bd/Test_AXI_Master_simple_v1_0_hw_1/Test_AXI_Master_simple_v1_0_hw_1_ooc.xdc
